#!/usr/bin/env bash
# Build and install kTile: KCM (System Settings) + KWin script, via CMake.
#
# Usage:
#   ./install-kcm.sh                    # install under ~/.local
#   ./install-kcm.sh /usr/local         # system-wide (needs write access)
#
# To remove an install from the same prefix:
#   ./uninstall-kcm.sh                  # or ./uninstall-kcm.sh /usr/local
#   ./uninstall-kcm.sh --build-dir build-cmake   # exact file list from CMake manifest
#
# If cmake is missing, install build deps:
#   Fedora:
#     sudo dnf install cmake gcc-c++ extra-cmake-modules \
#       qt6-qtbase-devel qt6-qtdeclarative-devel \
#       kf6-kcmutils-devel kf6-kconfig-devel kf6-kcoreaddons-devel kf6-ki18n-devel
#   Arch:
#     sudo pacman -S --needed cmake extra-cmake-modules base-devel \
#       qt6-base qt6-declarative kcmutils kconfig kcoreaddons ki18n
#   Ubuntu/Debian:
#     sudo apt install cmake build-essential extra-cmake-modules \
#       qt6-base-dev qt6-declarative-dev \
#       libkf6kcmutils-dev libkf6config-dev libkf6coreaddons-dev libkf6i18n-dev
#
# RPM packaging: see PACKAGING.md and packaging/fedora/ktile.spec
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
PREFIX="${1:-$HOME/.local}"
CMAKE="${CMAKE:-cmake}"

if ! command -v "$CMAKE" >/dev/null 2>&1; then
    echo "error: '$CMAKE' not found."
    echo
    echo "Install build dependencies, for example:"
    echo "  Fedora:"
    echo "    sudo dnf install cmake gcc-c++ extra-cmake-modules \\"
    echo "      qt6-qtbase-devel qt6-qtdeclarative-devel \\"
    echo "      kf6-kcmutils-devel kf6-kconfig-devel kf6-kcoreaddons-devel kf6-ki18n-devel"
    echo "  Arch:"
    echo "    sudo pacman -S --needed cmake extra-cmake-modules base-devel \\"
    echo "      qt6-base qt6-declarative kcmutils kconfig kcoreaddons ki18n"
    echo "  Ubuntu/Debian:"
    echo "    sudo apt install cmake build-essential extra-cmake-modules \\"
    echo "      qt6-base-dev qt6-declarative-dev \\"
    echo "      libkf6kcmutils-dev libkf6config-dev libkf6coreaddons-dev libkf6i18n-dev"
    echo
    echo "For a binary package instead of building from source, see PACKAGING.md"
    exit 1
fi

BUILD="$ROOT/build-cmake"
echo "Configuring kTile with prefix: $PREFIX"
"$CMAKE" -B "$BUILD" -S "$ROOT" \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-RelWithDebInfo}" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
"$CMAKE" --build "$BUILD" --parallel
"$CMAKE" --install "$BUILD"

echo
echo "Installed KWin script under: $PREFIX/share/kwin/scripts/org.kde.ktile/"
echo "Enable it in: System Settings → Window Management → KWin Scripts → kTile"
echo
echo "Reload the KWin script after edits (otherwise KWin keeps the old main.js in memory):"
echo "  Easiest: open kTile in System Settings and click Apply."
echo "  Or use qdbus (many Fedora installs do not ship qdbus6):"
echo "    qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting unloadScript org.kde.ktile \\"
echo "      && qdbus org.kde.KWin /Scripting org.kde.kwin.Scripting start"
echo "  If qdbus cannot find org.kde.kwin.Scripting on /Scripting, run:"
echo "    busctl introspect org.kde.KWin /Scripting"
echo ""
echo "The DBus service ktile-session-helper must be running to open the KCM (KWin calls it via DBus)."
echo "Binary: $PREFIX/bin/ktile-session-helper — the shortcut itself is a KWin action (Window Management)."
echo

if [[ "$PREFIX" != /usr* ]]; then
  ENV_DIR="$HOME/.config/plasma-workspace/env"
  ENV_FILE="$ENV_DIR/ktile-paths.sh"
  mkdir -p "$ENV_DIR"
  cat >"$ENV_FILE" <<EOF
#!/usr/bin/env sh
# Auto-generated by kTile installer for user-prefix installs.
export QT_PLUGIN_PATH="$PREFIX/lib64/plugins:$PREFIX/lib/plugins:$PREFIX/lib64/qt6/plugins:$PREFIX/lib/qt6/plugins\${QT_PLUGIN_PATH:+:\$QT_PLUGIN_PATH}"
export QML2_IMPORT_PATH="$PREFIX/lib64/qml:$PREFIX/lib/qml\${QML2_IMPORT_PATH:+:\$QML2_IMPORT_PATH}"
export XDG_DATA_DIRS="$PREFIX/share:\${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
EOF
  chmod +x "$ENV_FILE"

  # CMake installs autostart under $PREFIX/etc/xdg/autostart — Plasma does not load that path.
  # ~/.config/autostart is always scanned; use absolute Exec so PATH need not include ~/.local/bin.
  AUTOSTART_DIR="$HOME/.config/autostart"
  mkdir -p "$AUTOSTART_DIR"
  cat >"$AUTOSTART_DIR/ktile-session-helper.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=kTile session helper
Comment=D-Bus helper for kTile; KWin script calls org.kde.ktile to open the KCM
Exec=$PREFIX/bin/ktile-session-helper
X-KDE-autostart-phase=1
OnlyShowIn=KDE;
NoDisplay=true
EOF

  echo "Plasma autostart (shortcut daemon):"
  echo "  $AUTOSTART_DIR/ktile-session-helper.desktop"
  echo "Start the daemon now (before next login):"
  echo "  $PREFIX/bin/ktile-session-helper &"
  echo

  echo "User prefix install: Qt must find the KCM plugin. For example:"
  echo "  export QT_PLUGIN_PATH=\"$PREFIX/lib64/qt6/plugins:$PREFIX/lib/qt6/plugins\${QT_PLUGIN_PATH:+:\$QT_PLUGIN_PATH}\""
  echo "  export QML2_IMPORT_PATH=\"$PREFIX/lib64/qml:$PREFIX/lib/qml\${QML2_IMPORT_PATH:+:\$QML2_IMPORT_PATH}\""
  echo "  export XDG_DATA_DIRS=\"$PREFIX/share:\${XDG_DATA_DIRS:-/usr/local/share:/usr/share}\""
  echo
  echo "Installed persistent Plasma env file:"
  echo "  $ENV_FILE"
  echo "Log out and back in (or reboot) so app-launcher System Settings picks it up."
  echo "For immediate test in this shell, run:"
  echo "  . \"$ENV_FILE\" && kcmshell6 kcm_ktile"
  echo
fi
echo "Test KCM:  kcmshell6 kcm_ktile"
echo "Or:        systemsettings → Window Management → kTile"
